spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url:  jdbc:mysql://localhost:3306/restaurant
  jpa:
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
server:
  servlet:
    context-path: /restaurant
